### ISSUE TITLE
call fails on openSUSE Tumbleweed as there is no /etc/SuSE-release

### ISSUE THREAD

**Issue by okurz** [jnweiger/osc-plugin-install#1]
## observation

on a recent openSUSE Tumbleweed there is no file `/etc/SuSE-release` but only `/etc/os-release` from package openSUSE-release as a replacement.

A use of the plugin fails, e.g.

```
# osc in perl-Devel-Trace
https://api.opensuse.org/search/published/binary/id?match=%40name%3D%27perl-Devel-Trace%27
using /etc/SuSE-release to match build platforms
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/var/lib/osc-plugins/osc-install.py", line 305, in do_install
    arch_words = self._read_system_name(etc_S_r, opts)
  File "/var/lib/osc-plugins/osc-install.py", line 559, in _read_system_name
    text = open(file).read()
IOError: [Errno 2] No such file or directory: '/etc/SuSE-release'
```

## steps to reproduce

* install openSUSE Tumbleweed
* `zypper in osc osc-plugin-install`
* `osc in perl-Devel-Trace`
* add OBS credentials
* observe error

## suggestion

Use `/etc/os-release` instead of `/etc/SuSE-release` or use one as the fallback to the other.

**Comment by andreasstieger** [comment]
This is [boo#1009432](https://bugzilla.opensuse.org/show_bug.cgi?id=1009432).

**Comment by okurz** [comment]
proposed patch https://build.opensuse.org/package/view_file/home:okurz:branches:openSUSE:Tools/osc-plugin-install/boo%231009432_replace_etc_suse_release_by_os_release.patch?expand=1

**Comment by okurz** [comment]
I incorporated the above change in a newly created project https://github.com/openSUSE/osc-plugin-install
